defaults:
  - default.yaml

# use "ddp_find_unused_parameters_true" in scenarios with unused parameters
strategy: ddp

accelerator: gpu
devices: 4 # GPUs per node — match --gpus-per-node in slurm sh script
num_nodes: 2
sync_batchnorm: True
